publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "kuka1/iiwa_arm_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6"]
    pos1: [0.0, -1.0, 0.0, 0.785, 0.0, 0.785, 0.2]
    pos2: [0.0, -0.6, 0.1, 0.0, 0.785, 0.0, 0.0]
    pos3: [-0.2, -0.2, 0.0, -0.785, 0.0, 0.0, -0.2]
    pos4: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos5: [-0.2, -0.2, 0.0, -0.785, 0.0, 0.0, -0.2]
    pos6: [0.0, -0.6, 0.1, 0.0, 0.785, 0.0, 0.0]

    joints:
      - kuka1/joint_a1
      - kuka1/joint_a2
      - kuka1/joint_a3
      - kuka1/joint_a4
      - kuka1/joint_a5
      - kuka1/joint_a6
      - kuka1/joint_a7
